services:
  - type: web
    name: contactify-backend
    env: docker
    plan: free
    region: oregon
    branch: main
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: DB_URL
        value: your-production-mysql-host:3306
      - key: DB_USER
        value: your_production_db_user
      - key: DB_PASSWORD
        value: your_production_db_password
      - key: DDL_AUTO
        value: validate  # Important for production (not 'update')
      - key: CORS_ALLOWED_ORIGINS
        value: https://contactify.vercel.app